version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server
    restart: always
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
      - ./lorawan-devices:/opt/lorawan-devices
    ports:
      - 8000:8000

  chirpstack-gateway-bridge-au915:
    image: chirpstack/chirpstack-gateway-bridge
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - chirpstack-application-server

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    restart: always
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    ports:
      - 8080:8080
