version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server
    restart: always
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
      - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - db
      - mosquitto
      - redis
    ports:
      - 8080:8080

  chirpstack-gateway-bridge-au915:
    image: chirpstack/chirpstack-gateway-bridge
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
      - chirpstack-application-server

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    restart: always
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - mosquitto
      - db

  db:
    image: postgres:14-alpine
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: med
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: medicoes
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - datapostgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  datapostgres:
  redisdata:
